# -*- coding: utf-8 -*-
"""python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A4UAKh54Kk5qPnKyHFl8M3eol0y36VYU
"""

dias = int(input("Quantos dias alugados?"))
km = float(input("Quantos Km rodados?"))
preco = (dias*10)+(km*50)
print("O total a pagar é {}".format(preco))