# -*- coding: utf-8 -*-
"""python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A4UAKh54Kk5qPnKyHFl8M3eol0y36VYU
"""

import random
aluno1 = input("Digite um aluno: ")
aluno2 = input("Digite um aluno: ")
aluno3 = input("Digite um aluno: ")
aluno4 = input("Digite um aluno: ")


sort = random.randint(1,4)
if sort == 1:
  print(aluno1)
if sort == 2:
  print(aluno2)
if sort == 3:
  print(aluno3)
if sort == 4:
  print(aluno4)