# -*- coding: utf-8 -*-
"""python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A4UAKh54Kk5qPnKyHFl8M3eol0y36VYU
"""

a = int(input("Digite um número:"))
ant = a - 1
suc = a + 1
print("Você digitou o número {}, o antecessor é {} e o sucessor {}".format(a,ant,suc))