# -*- coding: utf-8 -*-
"""python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A4UAKh54Kk5qPnKyHFl8M3eol0y36VYU
"""

import math
ad = float(input("Digite o cateto adjacente: "))
op = float(input("Digite o cateto oposto: "))
 
hip = math.sqrt(math.pow(ad,2)+math.pow(op,2))
print("Os catetos são {} e {} e a hipotenusa é {}".format(ad,op,hip))