# -*- coding: utf-8 -*-
"""python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A4UAKh54Kk5qPnKyHFl8M3eol0y36VYU
"""

from math import factorial
a = int(input("Digite um número: "))
fat = math.factorial(a)
print("O fatorial de {} é {}".format(a,fat))