# -*- coding: utf-8 -*-
"""python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A4UAKh54Kk5qPnKyHFl8M3eol0y36VYU
"""

celsius = float(input("Qual a temperatura em °C?"))
fah = (celsius*9)/5 + 32
print("{} graus Celsius correspondem a {} graus fahrenheit".format(celsius,fah))