# -*- coding: utf-8 -*-
"""python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A4UAKh54Kk5qPnKyHFl8M3eol0y36VYU
"""

a = float(input("Digite uma distância em metros:"))
km = a/1000
cm = a*100
dm = a*10
print("A distância em {} em metros equivale a".format(a))
print("{}km, {}cm, {}dm".format(km,cm,dm))