# -*- coding: utf-8 -*-
"""python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A4UAKh54Kk5qPnKyHFl8M3eol0y36VYU
"""

a = float(input("Digite um número:"))
dobro = a*2
triplo = a*3
raiz = a**(1/2)
print("Você digitou o número {}, o dobro é {}, o triplo é {} e a raiz quadrada é {}".format(a,dobro,triplo,raiz))