# -*- coding: utf-8 -*-
"""python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A4UAKh54Kk5qPnKyHFl8M3eol0y36VYU
"""

from math import degrees,radians
a = int(input("Digite um valor em graus: "))

rad = math.radians(a)

print("{} graus é igual a {} radianos".format(a,rad))