# -*- coding: utf-8 -*-
"""python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A4UAKh54Kk5qPnKyHFl8M3eol0y36VYU
"""

import math
num = float(input("Digite um número:"))
numero = math.floor(num)
print("O número {} tem a parte o inteira {}".format(num,numero))