# -*- coding: utf-8 -*-
"""python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A4UAKh54Kk5qPnKyHFl8M3eol0y36VYU
"""

import math
angulo = float(input("Digite o ângulo que você deseja: "))
a = math.radians(angulo) 
sen = math.sin(a)
cos = math.cos(a)
tang = math.tan(a)
print("O angulo de {} tem seno de {}".format(angulo,sen))
print("O angulo de {} tem cosseno de {}".format(angulo,cos))
print("O angulo de {} tem tangente de {}".format(angulo,tang))