# -*- coding: utf-8 -*-
"""python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A4UAKh54Kk5qPnKyHFl8M3eol0y36VYU
"""

a = float(input("Digite um número: "))
b = float(input("Digite outro número: "))

c = a + b

print("A primeiro número é {}, o segundo é {} e a soma deles é {}".format(a,b,c))